config/routes.rb
Rails.application.routes.draw do
  resources :topics do
    resources :posts
  end

  mount GcaSsoClient::Engine => '/'
  root :to => "topics#index"
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
  
  after_save :touch_topic
  
  def touch_topic
    topic.touch
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :posts, dependent: :destroy
  
  accepts_nested_attributes_for :posts, reject_if: :all_blank
end

app/models/user.rb
class User < GcaSsoClient::User
  has_many :posts
  has_many :topics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include GcaSsoClient::Authentication
  
  protect_from_forgery with: :exception
  force_ssl unless Rails.env.development?
  
  before_action :authenticate_user!
  before_action :validate_session
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  skip_before_action :authenticate_user!
  layout 'application'

  def show
    @exception       = env['action_dispatch.exception']
    @status_code     = ActionDispatch::ExceptionWrapper.new(env, @exception).status_code
    @rescue_response = ActionDispatch::ExceptionWrapper.rescue_responses[@exception.class.name]
    view = [500, 404].include?(@status_code) ? @status_code.to_s : :show

    respond_to do |format|
      format.html { render view, status: @status_code, layout: !request.xhr? }
      format.xml  { render nothing: :true, status: @status_code }
      format.json { render nothing: :true, status: @status_code }
    end
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]
  before_action :set_topic, only: [:create, :edit]
  before_action :current_user_acts_as_owner, only: [:edit, :update]
  before_action :current_user_acts_as_admin, only: [:destroy]
  
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = @topic.posts.new(post_params)
    @post.user_id = current_user.id
    
    if @post.save
      redirect_to @post.topic, notice: "Successfully created your post."
    else
      render action: :new, error: "An error occurred while trying to create your post."
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post.topic, notice: 'Your post was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Your post was successfully deleted.'
  end
  
  protected
  
  def current_user_acts_as_owner
    redirect_to topics_url, error: "You do not have privileges to perform that action." if @post.user_id == current_user.id
  end
  
  def post_params
    params.require(:post).permit(:content)
  end

  def set_post
    @post = Post.find(params[:id])
  end
  
  def set_topic
    @topic = Topic.find(params[:topic_id])
  end
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :current_user_acts_as_owner, only: [:edit, :update]
  before_action :current_user_acts_as_admin, only: [:destroy]
  
  def index
    @topics = Topic.all.order('updated_at DESC')
  end

  def show
    @post = Post.new(topic_id: @topic.id)
  end
  
  def new
    @topic = Topic.new
    @topic.posts.build(user_id: current_user.uid)
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id
        
    if @topic.save
      redirect_to @topic, notice: "Successfully created your thread."
    else
      render action: :new, error: "An error occurred while trying to create your thread."
    end
  end

  def edit
  end

  def update
    if @topic.update(topic_params)
      redirect_to @topic, notice: 'Your topic was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @topic.destroy
    redirect_to topics_url, notice: 'Your topic and all associated posts were successfully deleted.'
  end
  
  protected
  
  def current_user_acts_as_owner
    redirect_to topics_url, error: "You do not have privileges to perform that action." if @topic.user_id == current_user.id
  end
  
  def set_topic
    @topic = Topic.find(params[:id])
  end
  
  def topic_params
    params.require(:topic).permit(:title, posts_attributes: [:content, :user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include GcaSsoClient::ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/topic_helper.rb
module TopicHelper
end

app/views/layouts/_modal_idle.html.erb
<div id="modalIdle" class="modal fade" tabindex="-1" aria-labelledby="modalWarningLabel" aria-hidden="true" data-redirect="<%= gca_sso_client.idle_url %>">
	<div class="modal-dialog">
		<div class="modal-content">
		  <div class="modal-header">
		    <h3 class="modal-title" id="myModalLabel">Still There?</h3>
		  </div>
		  <div class="modal-body">
			<h5>Your session appears to be idle.</h5>
	
		    <p>If you'd like to continue your session, please click below. Otherwise, your session will end in <strong><span id="modalIdleCounter">10</span> seconds.</strong></p>
		  </div>
		  <div class="modal-footer">
		    <button class="btn btn-info" id="idle_reset" data-dismiss="modal" aria-hidden="true">Continue</button>
		  </div>
		</div>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<%= nav_bar fixed: :top, brand: "GCA Discussions", brand_link: main_app.root_url, responsive: true do %>
    <%= menu_group do %>
		<% if user_signed_in? %>
			<%= menu_item "Topics", main_app.topics_url %>
			<%= menu_item "New Topic", main_app.new_topic_url %>
			<%= menu_item "Users", gca_sso_client.users_url if current_user.acts_as(:admin) %>
			<%= menu_divider %>
			<%= menu_item "Sign out (#{current_user.first_name})", gca_sso_client.signout_url, :method => :delete %>

		<% else %>
			<%= menu_item "Sign in", gca_sso_client.signin_url %>
		<% end %>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Greater Colorado Anesthesia &#8212; Discussions</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <% [57,72,114,144].each do |p| %>
  <%= favicon_link_tag "ios-#{p}x#{p}.png", rel: 'apple-touch-icon', type: 'image/png', sizes: "#{p}x#{p}" %>
  <% end %>
</head>
<body>

<%= render "layouts/navigation" %>

<div class="container">
    <%= bootstrap_flash %>
	<%= render "layouts/modal_idle" if user_signed_in? %>
    <%= yield %>
</div>

<div class="navbar navbar-fixed-bottom visible-desktop"></div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for [@topic, @post], html: {role: "form"} do |f| %>
	<div class="form-group">
		<% if @post.new_record? %><%= f.label :content, "Your Reply" %><% end %>
		<%= f.text_area :content, required: true, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.submit @post.new_record? ? "Create" : "Update", class: "btn btn-success" %>
	</div>
<% end %>

app/views/posts/edit.html.erb
<h3>Editing Your Reply</h3>

<div class="row">
	<div class="col-md-10">
		<%= render partial: "posts/form" %>
	</div>
</div>

app/views/topics/index.html.erb
<div class="row">
	<div class="col-sm-12">
		<div class="panel panel-warning">
			<div class="panel-heading">
				<h4 class="panel-title">Reminder</h4>
			</div>
			<div class="panel-body">
				<p>Please remember, <strong>all</strong> content posted on this forum is open to all GCA clinical employees. Please use respect when discussing sensitive topics.</p>
			</div>
		</div>
	</div>
</div>

<h3>Discussion Topics</h3>

<%= link_to "Start a New Topic", new_topic_url, class: "btn btn-success pull-right" %>

<table class="table table-striped" id="topics">
  <thead>
    <tr>
      <th>Title</th>
      <th class="hidden-xs">Started By</th>
      <th>Replies</th>
      <th>Last Activity</th>
    </tr>
  </thead>

  <tbody>
	<% unless @topics.empty? %>
	    <% @topics.each do |topic| %>
	      <tr class="topic">
			<td><%= link_to topic.title, topic %></td>
			<td class="hidden-xs"><%= topic.user %></td>
			<td><%= topic.posts.size - 1 %></td>
			<td><%= distance_of_time_in_words topic.updated_at, Time.now %> ago <small class="text-muted hidden-xs">by <%= topic.posts.last.user %></small></td>
	      </tr>
	    <% end %>
	<% else %>
		<tr><td>No topics found</td><td></td><td></td><td></td></tr>
	<% end %>
  </tbody>
</table>

app/views/topics/new.html.erb
<h3>Start a New Topic</h3>

<%= form_for @topic, html: {role: "form"} do |f| %>
	<div class="row">
		<div class="col-md-10">
			<div class="form-group">
				<%= f.label :title %>
				<%= f.text_field :title, required: true, class: "form-control" %>
			</div>
		
			<div class="form-group">
				<%= f.fields_for :posts do |p| %>
					<%= f.label :content %>
					<%= p.text_area :content,  required: true, class: "form-control" %>
					<%= p.hidden_field :user_id %>
				<% end %>
			</div>
		
			<div class="form-group">
				<%= f.submit "Create", class: "btn btn-success" %>
			</div>
		</div>
	</div>
<% end %>

app/views/topics/show.html.erb
<h2><%= @topic.title %> <small class="text-muted">Started by <%= @topic.user %></small></h2>

<ul class="list-unstyled" id="posts">
	<% @topic.posts.each do |post| %>
	<li>
		<div class="row">
			<div class="col-sm-7">
				<p><%= simple_format post.content %></p>
				<% if current_user == post.user %>
				<small><%= link_to "Edit", edit_topic_post_url(@topic, post) %></small>
				<% end %>
			</div>
			<div class="col-sm-1 hidden-sm hidden-xs">
				<h1><%= post.user.initials %></h1>
			</div>
			<div class="col-sm-2">
				<%= message_user_link post.user %><br/>
				<small>
					<%= post.created_at.strftime("%A, %B %e") %><br/>
					<%= post.created_at.strftime("%l:%M%P") %><% if post.created_at != post.updated_at %> <strong>(Edited)</strong><% end %></small>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-7">
				<hr/>				
			</div>
		</div>
	</li>
	<% end %>
</ul>

<%= link_to "Destroy", topic_url, method: :delete, class: "pull-right btn btn-danger" if current_user.acts_as(:admin) %>

<% if @topic.closed? %>
<div class="row">
	<div class="col-sm-7">
		<p class="text-muted">This topic has been closed.</p>
	</div>
</div>
<% else %>
<div class="row">
	<div class="col-sm-7">
		<%= render partial: "posts/form" %>
	</div>
</div>
<% end %>